# NOTE: modify settings to appropriate input/paths and parametersbefore running
# Number of job in the pipeline (in parenthesis the name of the job in the cluster)

# Dataset for pipelines outputs
OUTPUT_DATASET: waste_water/
# Raw Input Dataset hdfs path
INPUT_ROOT_PATH: &INPUT_ROOT_RAW waste_water/rawfiles
# Current run sub folder. All outputs created under this folder
RUN_FOLDER: output


# job 1 (Trimmomatic)
Trimmomatic:
  INPUT_ROOT : waste_water/rawfiles
  OUTPUT_SINGLE : output/trim/single
  OUTPUT_PAIRED : output/trim/pair
  OUTPUT_UNPAIRED : output/trim/unpair
  JAR: Tools/trimmomatic/trimmomatic-0.39.jar
  ADAPTER_PAIR: Tools/trimmomatic/adapters/NexteraPE-PE.fa
  ADAPTER_SINGLE: Tools/trimmomatic/adapters/TruSeq3-SE.fa
  SAVE_UNPAIRED : True
  USE_CUTADAPT : True # use True to run CUTADAPT on R2 files or False to skip
  IS_RNA : False       # use True for RNA or False for DNA
  LOGS_ROOT : Logs/ww/Trimmomatic
  # command args
  PHRED : phred33
  LEADING : 3
  TRAILING : 3
  SLIDINGWINDOW : '4:15'
  MINLEN : 36
  THREADS : 4

# job 2 (Nextgenmap)
# for nextgenmap
Nextgenmap :
  INPUT_ROOT :  trim/pair
  OUTPUT_ROOT : NGM/
  REFERENCE_FILE : References/Homo_sapiens.GRCh38.dna.primary_assembly.fa
  MIN-IDENTITY : 0.95
  MIN-RESIDUES : 0.75
  THREADS : 4
  LOGS_ROOT : Logs/NGM
  VERY_FAST : True  ### True to run ngm with parameter '--very-fast'. Read NGM docs for more about this parameter.
  INSTALL_NGM : False


# job 3 (ConvertSam2BamUnmapped)
FilterSAM:
  INPUT_ROOT : NGM/
  OUTPUT_BAM : Nonhuman/bam
  THREADS : 4

# As job 4 (SortNConvert)
SortConvert:
  INPUT_ROOT : Nonhuman/bam
  OUTPUT_FASTQ : Nonhuman/sorted
  SPLIT_PAIRS : False # True to split into separate fastq files for R1 and R2 reads for paired end files, False to create single fastq file
  THREADS : 4

# job 5 (kraken)
Kraken :
    INPUT_ROOT : Nonhuman/sorted
    OUTPUT_ROOT : Kraken/
    KRAKEN_PATH : Tools/kk2.1.2
    KRAKEN_DB_PATH : References/k2_pluspf_20240605
    SAVE_FULL_OUTPUT : True
    THREADS : 4

# job 6 (Bracken)
Bracken:
    INPUT_ROOT : Kraken/report
    OUTPUT_ROOT : Braken/
    KRAKEN_DB_PATH : References/k2_pluspf_20240605 #/Projects/HPV_meta/References/viral_april_2022 #References/k2_pluspf_20240605
    THREADS : 4
    READ_LENGTH : 150







